version: "3.9"
services:
  backend:
    build: ./backend
    profiles: ["app"]
    ports:
      - "3040:3040"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  frontend:
    build: ./frontend
    profiles: ["app"]
    ports:
      - "8081:80"
    environment:
      API_URL: http://localhost:3040
  nginx:
    image: nginx
    profiles: ["test"]
    labels:
      de.danielr1996.bashdoard.name: Nginx
      de.danielr1996.bashdoard.url: https://nginx.app.danielr1996.de
      de.danielr1996.bashdoard.icon: /favicon.ico
      de.danielr1996.bashdoard.id: nginx
  apache:
    image: nginx
    profiles: ["test"]
    labels:
      de.danielr1996.bashdoard.name: Apache2
      de.danielr1996.bashdoard.url: https://apache.app.danielr1996.de
      de.danielr1996.bashdoard.icon: /favicon.png
      de.danielr1996.bashdoard.id: apache