version: "3.9"
services:
  backend:
    image: ghcr.io/danielr1996/bashdoard-backend
    ports:
      - "8080:8080"
    volumes:
      - C:\\Users\\danie\.kube\config:/root/.kube/config
    environment:
      KUBECONFIG: /root/.kube/config
  frontend:
    image: ghcr.io/danielr1996/bashdoard-frontend
    ports:
      - "8081:80"
    environment:
      API_URL: http://localhost:8080