name: Publish Helm Chart
on:
  push:
    branches:
      - 'main'
jobs:
  push_chart:
    name: Push helm chart to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: bashdoard
          repository: danielr1996
          tag: 0.1.0
          path: helm 
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}